# Generated by Django 2.1.2 on 2018-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20181103_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatch_time',
            field=models.DateTimeField(null=True),
        ),
    ]
