# Generated by Django 2.1.2 on 2018-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
