# Generated by Django 2.1.2 on 2018-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_item_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
