# Generated by Django 2.1.2 on 2018-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
