# Generated by Django 2.1.2 on 2018-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_Data', '0002_auto_20181106_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeA', models.CharField(max_length=200)),
                ('palceB', models.CharField(max_length=200)),
                ('distance', models.FloatField(default=0.0)),
            ],
        ),
    ]
