# Generated by Django 2.1.2 on 2018-11-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_weight',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
